# Generated by Django 5.0 on 2025-03-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.workshop'),
        ),
    ]
